name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
  workflow_dispatch:

env:
  ACR_NAME: ${{ vars.ACR_NAME }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AZURE_CREDENTIALS

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Login ACR
        run: |
          echo $ACR_NAME
          az acr login --name $ACR_NAME

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
